<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mailinator_email_inbox</name>
   <tag></tag>
   <elementGuidId>a5f6d745-319b-477e-bf2e-29d8d2e6960a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;InboxCtrl&quot;]/section/div/div[2]/ul/li[1]/ul/li/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
