<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>O21_RegisterPw_NewPw_Confirm_Label</name>
   <tag></tag>
   <elementGuidId>b57afbdb-4b24-4d55-8498-d0b2b1de94e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;e-setuppassword&quot;]/div/div/div[3]/div/form/div[2]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
